name: Manually release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Call dev/make-distribution.sh
      run: |
        export MAVEN_OPTS="-Xss64m -Xmx4g -XX:ReservedCodeCacheSize=1g"
        ./dev/make-distribution.sh --name xyz --pip --tgz -Phive -Phive-thriftserver -Pkubernetes -Phadoop-3.2 -Phadoop-cloud
        ls -l

    - name: Build the Docker image
      run: |
        mkdir -p temp
        mv spark-*-bin-xyz.tgz temp/
        cd temp
        tar xzvf spark-*-bin-xyz.tgz
        rm spark-*-bin-xyz.tgz
        mv spark-*-bin-xyz spark-bin-xyz
        pwd
        ls -l
        cd spark-bin-xyz
        ./bin/docker-image-tool.sh -t spark-xyz build
        ./bin/docker images
